language: php

sudo: false

php:
    - 7.4
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/simple-phpunit
